polling_interval: 15m

rate_limit:
  # minimum gap between requests to the same ATS
  min_delay: 720s # 12 mins

# Notification settings (options: log, slack)
notification:
  type: slack
  webhook_url: "${SLACK_WEBHOOK_URL}" # injected from GitHub secrets

filters:
  max_age: 24h # age of a job posting to be considered fresh (1h to 24h)
  title_keywords:
    - software engineer
    - software developer
    - software development engineer
    - backend
    - golang
    - python
    - distributed systems
    - member of technical staff
    - ai engineer
    - agentic ai engineer
    - mts
    - sde
    - swe

  title_exclude_keywords:
    - manager
    - intern
    - staff software engineer
    - staff member of technical staff
    - director
    - principal
    - scientist
    - full stack
    - full-stack
    - ios
    - android
    - frontend
    - embedded
    - forward deployed
    - sr staff

  locations:
    - United States
    - United States of America
    - US
    - USA
    - Remote
    - San Francisco
    - CA
    - California
    - New York
    - NY
    - San Jose
  exclude_locations:
    - Canada
    - Cairo
    - Germany
    - Denmark

companies:
  - name: anthropic
    ats: greenhouse
    board_token: "anthropic"
    enabled: true

  - name: chime
    ats: greenhouse
    board_token: "chime"
    enabled: true

  - name: cohere
    ats: ashby
    board_token: "cohere"
    enabled: true

  - name: openai
    ats: ashby
    board_token: "openai"
    enabled: true

  - name: postman
    ats: greenhouse
    board_token: "postman"
    enabled: true

  - name: stripe
    ats: greenhouse
    board_token: "stripe"
    enabled: true

  - name: spotify
    ats: lever
    board_token: "spotify"
    enabled: true

  - name: palantir
    ats: lever
    board_token: "palantir"
    enabled: true

  - name: snowflake
    ats: ashby
    board_token: "snowflake"
    enabled: true

  - name: perplexity
    ats: ashby
    board_token: "perplexity"
    enabled: true

  - name: scaleai
    ats: greenhouse
    board_token: "scaleai"
    enabled: true

  - name: langchain
    ats: ashby
    board_token: "langchain"
    enabled: true

  - name: cloudflare
    ats: greenhouse
    board_token: "cloudflare"
    enabled: true

  - name: ramp
    ats: ashby
    board_token: "ramp"
    enabled: true

  - name: doordash
    ats: greenhouse
    board_token: "doordashusa"
    enabled: true

  - name: togetherai
    ats: greenhouse
    board_token: "togetherai"
    enabled: true

  - name: fireworksai
    ats: greenhouse
    board_token: "fireworksai"
    enabled: true

  - name: temporal
    ats: greenhouse
    board_token: "temporaltechnologies"
    enabled: true

  - name: glean
    ats: greenhouse
    board_token: "gleanwork"
    enabled: true

  - name: bill
    ats: greenhouse
    board_token: "billcom"
    enabled: true

  - name: envoy
    ats: ashby
    board_token: "envoy"
    enabled: true

  - name: databricks
    ats: greenhouse
    board_token: "databricks"
    enabled: true

  - name: roblox
    ats: greenhouse
    board_token: "roblox"
    enabled: true

  - name: coreweave
    ats: greenhouse
    board_token: "coreweave"
    enabled: true
  
  - name: slack
    ats: workday
    workday_url: "https://salesforce.wd12.myworkdayjobs.com/wday/cxs/salesforce/Slack"
    enabled: true

  - name: snapchat
    ats: workday
    workday_url: "https://snapchat.wd1.myworkdayjobs.com/wday/cxs/snapchat/snap"
    enabled: true

  - name: paloaltonetworks
    ats: workday
    workday_url: "https://paloaltonetworks.wd5.myworkdayjobs.com/wday/cxs/paloaltonetworks/panwexternalcareers"
    enabled: true

# TODO: add gem ATS