polling_interval: 5m

companies:
  - name: postman
    ats: greenhouse
    board_token: "postman"
    enabled: true

  - name: glean
    ats: greenhouse
    board_token: "gleanwork"
    enabled: true


filters:
  title_keywords:
    - software engineer
    - backend
    - sde
    - platform
    - infrastructure
  locations:
    - United States
    - US
    - Remote
    - San Francisco
    - CA
    - New York
    - San Jose
